name: Toto
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps: 
      - name: Recup du repo
        uses: actions/checkout@v3
      - name: test 1
        run: exit 1
      - name: test 2
        run: echo "test 2"
  Build:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Je build"
  Check:
    needs: [Test, Build]
    runs-on: ubuntu-latest
    if: always() && (needs.Test.result == 'failure' || needs.Build.result == 'failure')
    steps:
      - name: "Mail"
        run: echo "mail"