name: Toto
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps: 
      - name: Github
        run: echo '${{ toJSON(github) }}'
      - name: job
        run: echo '${{ toJSON(job) }}'
      - name: step
        run: echo '${{ toJSON(steps) }}'
      - name: Runner
        run: echo '${{ toJSON(runner) }}'