name: Toto
on: [push]
jobs:
  MonPremierJob:
    runs-on: ubuntu-latest
    steps: 
      - name: Afficher salut en console
        run: echo "Salut!"
      - name: Etape deux
        run: echo "Toto"