name: Toto
on: [push]
jobs:
  MonPremierJob:
    runs-on: ubuntu-latest
    steps: 
      - name: Recup du repo
        uses: actions/checkout@v3
        with:
          ref: "refs/SHA/95eccff6866"
      - name: afficher le contenu de mon job
        run: ls